modLoader = "javafml"
loaderVersion = "[1,)"
license = "Use-Restriction-License (URL)"
issueTrackerURL = "https://github.com/apfelmagnet32/invincible-cable/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Industrial Grid"
description = '''Adds an indestructible Create: Power Grid wire that never burns out from overload, plus high-range voltage/current/power gauges.'''
authors = "apfelmagnet32"

[[dependencies.'${mod_id}']]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.'${mod_id}']]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.'${mod_id}']]
    modId = "powergrid"
    type = "required"
    versionRange = "[0.6.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.'${mod_id}']]
    modId = "create"
    type = "required"
    versionRange = "[6.0.0,)"
    ordering = "AFTER"
    side = "BOTH"
